# permissions for end users to edit balancingrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: balancingrule-editor-role
rules:
- apiGroups:
  - loadbalancing.spike-mitigator.mmmknt.dev
  resources:
  - balancingrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loadbalancing.spike-mitigator.mmmknt.dev
  resources:
  - balancingrules/status
  verbs:
  - get
