apiVersion: spike-mitigation.mmmknt.dev/v1
kind: MitigationRule
metadata:
  name: mitigationrule-sample
spec:
  # Add fields here
  gatewayName: "gateway name"
  secretNamespace: "namespace of secret that is needed for spike mitigation"
  externalHost: "external host"
  externalAuthorizationRef:
    name: "secret name for authorization to external host"
    key: "key in secret's data for authorization to external host"
  internalHost: "internal host"
  hpaTriggerRate: 50
  mitigationTriggerRate: 80
  metricsStoreSecretRef:
    ddApiKeyRef:
      name: "secret name for datadog api key"
      key: "key in secret's data for datadog api key"
    ddAppKeyRef:
      name: "secret name for datadog app key"
      key: "key in secret's data for datadog app key"
  metricsCondition:
    metricsName: "the name of metrics that stores hpa"
    clusterName: "the name of kubernetes cluster that receives requests"
  monitoredHpaNamespace: "namespace that monitored hpa is in"
  monitoredHpaNames:
    - "hpa names that is target to judge to need mitigation or not"
